// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1, arg2) {
  return window['go']['proxy']['Options']['Run'](arg1, arg2);
}

export function Stop() {
  return window['go']['proxy']['Options']['Stop']();
}
